// Copy strings — EN / FI / RU. Single source of translation truth.

const COPY = {
  en: {
    nav: { bio: "Biography", concerts: "Concerts", repertoire: "Repertoire", recordings: "Recordings", press: "Press", gallery: "Gallery", media: "Media", news: "News", contact: "Contact" },
    hero: {
      eyebrow: "Violinist",
      name1: "Albert",
      name2: "Dilanyan",
      meta: ["Born 1998 · Yerevan", "Based in Moscow", "Stradivari, on loan"],
      quote: "A bow that thinks before it sings — phrasing of unusual intelligence and a tone that carries far past the back of the hall.",
      quoteCite: "Le Monde de la Musique",
      foot: "Season 2025 — 2026",
    },
    sec: {
      bio:        { num: "01", kicker: "Biography",  title: "A voice formed at the Gnessin school." , lede: "Trained in the Russian tradition, performing across Europe, Asia and the Middle East with a repertoire that runs from Bach to the present day." },
      concerts:   { num: "02", kicker: "Calendar",   title: "Upcoming engagements" , lede: "Recitals, concerto appearances and chamber programmes — selected dates from the current season." },
      repertoire: { num: "03", kicker: "Repertoire", title: "A living catalogue" , lede: "An evolving list of works held actively in performance — concerto, sonata and unaccompanied repertoire." },
      disco:      { num: "04", kicker: "Recordings", title: "On record" , lede: "Studio and live recordings, released under independent labels and broadcast by Radio France, BBC Radio 3 and Yle Klassinen." },
      press:      { num: "05", kicker: "Press",      title: "What the critics write" , lede: "" },
      gallery:    { num: "06", kicker: "Photography",title: "From the road" , lede: "Concert and portrait photography — selected frames from recent seasons." },
      media:      { num: "07", kicker: "Media",      title: "Watch & listen" , lede: "Live performances, studio sessions and conversations." },
      news:       { num: "08", kicker: "Journal",    title: "News & announcements" , lede: "" },
      contactT:   { lead: "Get in", lead2: "touch." },
    },
    bio: [
      "Albert Dilanyan studied violin at the Gnessin State Musical College in Moscow under the tradition that has shaped generations of soloists. From his earliest public appearances his playing has been distinguished by a clarity of architecture rare for his age — an interpreter who builds a phrase before he bows it.",
      "His concert work spans the canonical concerto repertoire alongside an active engagement with twentieth-century and contemporary Armenian composers. Recent seasons have seen recitals at the Moscow Conservatory Small Hall, the Helsinki Music Centre, and chamber appearances throughout Western Europe.",
      "Off the platform he is a committed teacher and curator of small festivals, returning regularly to Yerevan for masterclass work with young string players from across the Caucasus.",
    ],
    bioMeta: [
      ["Education",   "Gnessin State Musical College, Moscow"],
      ["Born",        "Yerevan, 1998"],
      ["Instrument",  "G. B. Guadagnini, on private loan"],
      ["Languages",   "Russian · Armenian · English · Finnish"],
    ],
    roles: [
      { num: "i.",   tag: "On stage · 2025",     h1: "The",  h2: "Soloist",          p: "Concerto appearances with the Finnish Radio Symphony, the Moscow State Academic Philharmonic, and the Royal Northern Sinfonia. The reading is unhurried and structural — a soloist who treats the orchestra as conversation rather than backdrop." },
      { num: "ii.",  tag: "Chamber · Verbier",   h1: "The",  h2: "Chamber Musician", p: "A long collaboration with pianist Anna Geniušas anchors a recital practice that pairs the German canon with twentieth-century Armenian and Soviet voices — Schnittke and Komitas alongside Brahms and Franck." },
      { num: "iii.", tag: "Komitas Hall · Yerevan", h1: "The",  h2: "Educator",         p: "Annual masterclass residencies at the Komitas State Conservatory and an ongoing programme of small festivals in regional Armenia. Teaching is not a sideline but a form of continued listening." },
      { num: "iv.",  tag: "Resonance Editions",  h1: "The",  h2: "Recording Artist", p: "Three studio albums to date with Resonance Editions and Yerevan Records. Sessions are conceived as documents — long takes, minimal editing, an ear toward the room rather than the microphone." },
    ],
    repertoire: [
      { h: "Concerto", items: [
        ["Bach",        "Concerti in A minor, E major, D minor (two violins)"],
        ["Mozart",      "Concerti Nos. 3, 4, 5"],
        ["Beethoven",   "Concerto in D, Op. 61"],
        ["Mendelssohn", "Concerto in E minor, Op. 64"],
        ["Brahms",      "Concerto in D, Op. 77"],
        ["Tchaikovsky", "Concerto in D, Op. 35"],
        ["Sibelius",    "Concerto in D minor, Op. 47"],
        ["Shostakovich","Concerto No. 1 in A minor, Op. 77"],
        ["Khachaturian","Concerto in D minor"],
      ]},
      { h: "Sonata & Recital", items: [
        ["Bach",       "Six Sonatas & Partitas, BWV 1001–1006"],
        ["Beethoven",  "Sonatas Nos. 5, 7, 9 (“Kreutzer”)"],
        ["Brahms",     "Sonatas Nos. 1, 2, 3"],
        ["Franck",     "Sonata in A major"],
        ["Debussy",    "Sonata in G minor"],
        ["Ravel",      "Tzigane · Sonata No. 2"],
        ["Prokofiev",  "Sonatas Nos. 1, 2"],
        ["Schnittke",  "Sonata No. 1"],
      ]},
      { h: "Unaccompanied & Modern", items: [
        ["Ysaÿe",       "Six Sonatas, Op. 27"],
        ["Bartók",      "Sonata for Solo Violin, Sz. 117"],
        ["Berio",       "Sequenza VIII"],
        ["Kurtág",      "Signs, Games and Messages"],
        ["Komitas / arr.","Six Armenian dances"],
        ["Mansurian",   "Selected miniatures"],
        ["Pärt",        "Fratres · Spiegel im Spiegel"],
      ]},
    ],
    pressItems: [
      { q: "Phrasing of unusual intelligence — Dilanyan plays the line, not the note.",                       s: "Le Monde de la Musique", c: "Paris" },
      { q: "A Sibelius of granite and ice. He has the long view that this concerto demands.",                  s: "Helsingin Sanomat",      c: "Helsinki" },
      { q: "The Armenian voice in him is unmistakable, even in Bach. There is a quietness here that listens.", s: "Kommersant",             c: "Moscow" },
      { q: "Among the most thoughtful violinists of his generation now before the public.",                    s: "The Strad",              c: "London" },
    ],
    newsItems: [
      { d: "April 2026",    t: "Debut at Wigmore Hall confirmed for spring 2027",         e: "A solo recital with pianist Anna Geniušas — Bach, Schnittke, Komitas — has been added to the Wigmore Hall calendar for March 2027.", c: "Engagement" },
      { d: "March 2026",    t: "New album Northbound out on Resonance Editions",          e: "Recorded across two weeks at the Sello Hall in Espoo, the disc pairs Sibelius with sonatas by Pärt and Mansurian.",                c: "Release" },
      { d: "January 2026",  t: "Masterclass residency in Yerevan",                         e: "A two-week masterclass series at the Komitas State Conservatory, open to advanced string students from across the region.",       c: "Teaching" },
      { d: "November 2025", t: "First prize, International Khachaturian Competition",      e: "Awarded the first prize and special audience prize in the violin category at the XX Khachaturian International Competition.",     c: "Award" },
    ],
    contact: {
      mgmt:  ["Management", ["European representation", "Albrecht & Strauch, Berlin", "office@albrecht-strauch.example"]],
      press: ["Press & enquiries", ["Erin Mäki, press officer", "press@albertdilanyan.example"]],
      direct:["Direct",        ["albert@albertdilanyan.example"]],
      social:["Social",        [["YouTube", "https://www.youtube.com/@АльбертАшотович-з8и"], ["Instagram", "—"], ["Spotify", "—"]]],
    },
    foot: "© 2026 Albert Dilanyan. All rights reserved. Site by studio—lentus.",
    misc: { play: "Listen", watch: "Watch", details: "Details", season: "2025 / 26 Season" },
    filters: ["All", "2026", "2025", "Past"],
    months: ["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"],
  },
  fi: {
    nav: { bio: "Elämäkerta", concerts: "Konsertit", repertoire: "Ohjelmisto", recordings: "Levytykset", press: "Lehdistö", gallery: "Galleria", media: "Media", news: "Uutiset", contact: "Yhteystiedot" },
    hero: {
      eyebrow: "Viulisti",
      name1: "Albert",
      name2: "Dilanyan",
      meta: ["Synt. 1998 · Jerevan", "Asuu Moskovassa", "Stradivari, lainassa"],
      quote: "Jousi joka ajattelee ennen kuin laulaa — fraseerausta poikkeuksellisella älyllä, ja sointi joka kantaa salin perille saakka.",
      quoteCite: "Le Monde de la Musique",
      foot: "Kausi 2025 — 2026",
    },
    sec: {
      bio:        { num: "01", kicker: "Elämäkerta",  title: "Gnessinin koulun muovaama ääni." , lede: "Koulutettu venäläisen koulukunnan parissa, esiintyy ympäri Eurooppaa, Aasiaa ja Lähi-itää ohjelmistolla, joka ulottuu Bachista nykypäivään." },
      concerts:   { num: "02", kicker: "Kalenteri",   title: "Tulevat konsertit" , lede: "Resitaaleja, konserttoesityksiä ja kamarimusiikkia — valikoituja päivämääriä tästä kaudesta." },
      repertoire: { num: "03", kicker: "Ohjelmisto",  title: "Elävä luettelo" , lede: "Kehittyvä lista teoksista, jotka ovat aktiivisesti esityksessä — konserttoja, sonaatteja ja sooloteoksia." },
      disco:      { num: "04", kicker: "Levytykset",  title: "Levyllä" , lede: "Studio- ja livetaltiointeja itsenäisillä levymerkeillä, lähetyksiä Radio Francen, BBC Radio 3:n ja Yle Klassisen kanavilla." },
      press:      { num: "05", kicker: "Lehdistö",    title: "Kriitikoiden sanoin" , lede: "" },
      gallery:    { num: "06", kicker: "Valokuvat",   title: "Tieltä" , lede: "Konsertti- ja muotokuvavalokuvausta — viime kausilta valikoituja otoksia." },
      media:      { num: "07", kicker: "Media",       title: "Katso & kuuntele" , lede: "Livetaltiointeja, studiosessioita ja keskusteluja." },
      news:       { num: "08", kicker: "Päiväkirja",  title: "Uutiset & ilmoitukset" , lede: "" },
      contactT:   { lead: "Ota", lead2: "yhteyttä." },
    },
    bio: [
      "Albert Dilanyan opiskeli viulunsoittoa Gnessinin valtion musiikkiopistossa Moskovassa siinä perinteessä, joka on muovannut sukupolvia solisteja. Ensiesiintymisistään lähtien hänen soittoaan on luonnehtinut iälleen harvinainen rakenteen kirkkaus — tulkki, joka rakentaa fraasin ennen kuin sen jousta vetää.",
      "Hänen konserttitoimintansa kattaa kanonisen konserttorepertuaarin sekä aktiivisen kiinnostuksen 1900-luvun ja nykyaikaisten armenialaisten säveltäjien teoksiin. Viimeisimmillä kausilla resitaaleja Moskovan konservatorion pienessä salissa, Helsingin Musiikkitalossa ja kamarimusiikkiesiintymisiä Länsi-Euroopassa.",
      "Lavan ulkopuolella hän on omistautunut opettaja ja pienten festivaalien kuraattori, palaa säännöllisesti Jerevaniin pitämään mestarikursseja Kaukasian alueen nuorille jousisoittajille.",
    ],
    bioMeta: [
      ["Koulutus",   "Gnessinin valtion musiikkiopisto, Moskova"],
      ["Synt.",      "Jerevan, 1998"],
      ["Soitin",     "G. B. Guadagnini, yksityislainassa"],
      ["Kielet",     "Venäjä · Armenia · Englanti · Suomi"],
    ],
    roles: [
      { num: "i.",   tag: "Lavalla · 2025",         h1: "",  h2: "Solisti",          p: "Konserttoesiintymisiä Radion sinfoniaorkesterin, Moskovan valtion akateemisen filharmonian ja Royal Northern Sinfonian kanssa. Tulkinta on kiireetön ja rakenteellinen — solisti, jolle orkesteri on keskustelukumppani, ei tausta." },
      { num: "ii.",  tag: "Kamarimusiikki · Verbier", h1: "", h2: "Kamarimuusikko",  p: "Pitkä yhteistyö pianisti Anna Geniušasin kanssa pitää koossa resitaalitoiminnan, joka yhdistää saksalaisen kaanonin 1900-luvun armenialaisiin ja neuvostoliittolaisiin ääniin — Schnittke ja Komitas Brahmsin ja Franckin rinnalla." },
      { num: "iii.", tag: "Komitas-sali · Jerevan", h1: "", h2: "Opettaja",          p: "Vuosittaisia mestarikurssiresidenssejä Komitas-konservatoriossa sekä jatkuva ohjelma pieniä festivaaleja Armenian alueilla. Opettaminen ei ole sivuhomma vaan jatkuvaa kuuntelua." },
      { num: "iv.",  tag: "Resonance Editions",     h1: "",  h2: "Levyttävä taiteilija", p: "Kolme studioalbumia tähän mennessä Resonance Editions- ja Yerevan Records -merkeillä. Sessiot ovat dokumentteja — pitkiä ottoja, vähäistä editointia, korva salin ääneen mikrofonin sijaan." },
    ],
    repertoire: [
      { h: "Konsertto", items: [
        ["Bach",        "Konsertot a-molli, E-duuri, d-molli (kahdelle viululle)"],
        ["Mozart",      "Konsertot nro 3, 4, 5"],
        ["Beethoven",   "Konsertto D-duuri, op. 61"],
        ["Mendelssohn", "Konsertto e-molli, op. 64"],
        ["Brahms",      "Konsertto D-duuri, op. 77"],
        ["Tšaikovski",  "Konsertto D-duuri, op. 35"],
        ["Sibelius",    "Konsertto d-molli, op. 47"],
        ["Šostakovitš", "Konsertto nro 1 a-molli, op. 77"],
        ["Hatšaturjan", "Konsertto d-molli"],
      ]},
      { h: "Sonaatti & resitaali", items: [
        ["Bach",       "Kuusi sonaattia & partitaa, BWV 1001–1006"],
        ["Beethoven",  "Sonaatit nro 5, 7, 9 (“Kreutzer”)"],
        ["Brahms",     "Sonaatit nro 1, 2, 3"],
        ["Franck",     "Sonaatti A-duuri"],
        ["Debussy",    "Sonaatti g-molli"],
        ["Ravel",      "Tzigane · Sonaatti nro 2"],
        ["Prokofjev",  "Sonaatit nro 1, 2"],
        ["Schnittke",  "Sonaatti nro 1"],
      ]},
      { h: "Soolot & moderni", items: [
        ["Ysaÿe",        "Kuusi sonaattia, op. 27"],
        ["Bartók",       "Sonaatti soolo­viululle, Sz. 117"],
        ["Berio",        "Sequenza VIII"],
        ["Kurtág",       "Signs, Games and Messages"],
        ["Komitas / sov.","Kuusi armenialaista tanssia"],
        ["Mansurjan",    "Valittuja miniatyyrejä"],
        ["Pärt",         "Fratres · Spiegel im Spiegel"],
      ]},
    ],
    pressItems: [
      { q: "Poikkeuksellisen älykästä fraseerausta — Dilanyan soittaa linjan, ei nuottia.",                                  s: "Le Monde de la Musique", c: "Pariisi" },
      { q: "Graniittinen ja jäinen Sibelius. Hänellä on se pitkä kaari, jota tämä konsertto vaatii.",                          s: "Helsingin Sanomat",      c: "Helsinki" },
      { q: "Hänen armenialainen äänensä on erehtymätön — myös Bachissa. Tässä on hiljaisuutta joka kuuntelee.",                s: "Kommersant",             c: "Moskova" },
      { q: "Sukupolvensa harkitsevimpia viulisteja, jotka ovat nyt yleisön edessä.",                                            s: "The Strad",              c: "Lontoo" },
    ],
    newsItems: [
      { d: "Huhtikuu 2026",     t: "Wigmore Hallin debyytti vahvistettu kevääksi 2027",       e: "Resitaali pianisti Anna Geniušasin kanssa — Bach, Schnittke, Komitas — on lisätty Wigmore Hallin kalenteriin maaliskuussa 2027.",          c: "Konsertti" },
      { d: "Maaliskuu 2026",    t: "Uusi albumi Northbound julkaistu Resonance Editionsilla", e: "Kahden viikon aikana Espoon Sellosalissa äänitetty levy yhdistää Sibeliuksen Pärtin ja Mansurjanin sonaatteihin.",                       c: "Julkaisu" },
      { d: "Tammikuu 2026",     t: "Mestarikurssi-residenssi Jerevanissa",                     e: "Kahden viikon mestarikurssisarja Komitas-konservatoriossa, avoin alueen edistyneille jousisoittajille.",                                  c: "Opetus" },
      { d: "Marraskuu 2025",    t: "Ensimmäinen palkinto Hatšaturjan-kilpailussa",            e: "XX kansainvälisen Hatšaturjan-kilpailun viululuokan ensimmäinen palkinto sekä erityinen yleisöpalkinto.",                                c: "Palkinto" },
    ],
    contact: {
      mgmt:  ["Manageri",       ["Eurooppalainen edustus", "Albrecht & Strauch, Berliini", "office@albrecht-strauch.example"]],
      press: ["Lehdistö",       ["Erin Mäki, lehdistövastaava", "press@albertdilanyan.example"]],
      direct:["Suoraan",        ["albert@albertdilanyan.example"]],
      social:["Sosiaalinen",    [["YouTube", "https://www.youtube.com/@АльбертАшотович-з8и"], ["Instagram", "—"], ["Spotify", "—"]]],
    },
    foot: "© 2026 Albert Dilanyan. Kaikki oikeudet pidätetään. Sivuston suunnittelu studio—lentus.",
    misc: { play: "Kuuntele", watch: "Katso", details: "Tiedot", season: "Kausi 2025 / 26" },
    filters: ["Kaikki", "2026", "2025", "Mennyt"],
    months: ["TAM","HEL","MAA","HUH","TOU","KES","HEI","ELO","SYY","LOK","MAR","JOU"],
  },
  ru: {
    nav: { bio: "Биография", concerts: "Концерты", repertoire: "Репертуар", recordings: "Записи", press: "Пресса", gallery: "Галерея", media: "Медиа", news: "Новости", contact: "Контакты" },
    hero: {
      eyebrow: "Скрипач",
      name1: "Альберт",
      name2: "Диланян",
      meta: ["Род. 1998 · Ереван", "Живёт в Москве", "Страдивари, в аренде"],
      quote: "Смычок, который мыслит, прежде чем запеть, — фразировка редкого ума и звук, доходящий до самых задних рядов зала.",
      quoteCite: "Le Monde de la Musique",
      foot: "Сезон 2025 — 2026",
    },
    sec: {
      bio:        { num: "01", kicker: "Биография",  title: "Голос, рождённый Гнесинской школой." , lede: "Воспитан в русской традиции; выступает в Европе, Азии и на Ближнем Востоке с репертуаром от Баха до наших дней." },
      concerts:   { num: "02", kicker: "Календарь",  title: "Предстоящие выступления" , lede: "Сольные концерты, выступления с оркестром и камерные программы — избранные даты текущего сезона." },
      repertoire: { num: "03", kicker: "Репертуар",  title: "Живой каталог" , lede: "Развивающийся список сочинений, активно исполняемых на сцене — концерты, сонаты и сольные произведения." },
      disco:      { num: "04", kicker: "Записи",     title: "На записи" , lede: "Студийные и концертные записи на независимых лейблах; трансляции Radio France, BBC Radio 3 и Yle Klassinen." },
      press:      { num: "05", kicker: "Пресса",     title: "Что пишут критики" , lede: "" },
      gallery:    { num: "06", kicker: "Фото",       title: "С дороги" , lede: "Концертная и портретная фотография — избранные кадры последних сезонов." },
      media:      { num: "07", kicker: "Медиа",      title: "Смотреть и слушать" , lede: "Концертные записи, студийные сессии и беседы." },
      news:       { num: "08", kicker: "Журнал",     title: "Новости и анонсы" , lede: "" },
      contactT:   { lead: "Связаться", lead2: "со мной." },
    },
    bio: [
      "Альберт Диланян учился игре на скрипке в Государственном музыкальном училище имени Гнесиных в Москве — в той традиции, что воспитала поколения солистов. С самых ранних публичных выступлений его игру отличает редкая для его возраста архитектурная ясность: исполнитель, выстраивающий фразу прежде, чем провести смычком.",
      "Концертная деятельность охватывает как канонический скрипичный репертуар, так и активный диалог с композиторами XX века и современной армянской музыкой. В последних сезонах — сольные концерты в Малом зале Московской консерватории, в Доме музыки Хельсинки и камерные выступления по Западной Европе.",
      "Помимо сцены, он — увлечённый педагог и куратор небольших фестивалей; регулярно возвращается в Ереван для проведения мастер-классов с молодыми струнниками со всего Кавказа.",
    ],
    bioMeta: [
      ["Образование", "Государственное музыкальное училище имени Гнесиных, Москва"],
      ["Род.",        "Ереван, 1998"],
      ["Инструмент",  "Дж. Б. Гваданьини, частная аренда"],
      ["Языки",       "Русский · Армянский · Английский · Финский"],
    ],
    roles: [
      { num: "i.",   tag: "На сцене · 2025",       h1: "",  h2: "Солист",            p: "Концертные выступления с Симфоническим оркестром радио Финляндии, МГАФО и Royal Northern Sinfonia. Прочтение неспешное и архитектурное — солист, для которого оркестр — собеседник, а не фон." },
      { num: "ii.",  tag: "Камерная · Вербье",     h1: "",  h2: "Камерный музыкант", p: "Долгое сотрудничество с пианисткой Анной Генюшас держит на себе сольную практику, в которой немецкий канон соседствует с армянскими и советскими голосами XX века — Шнитке и Комитас рядом с Брамсом и Франком." },
      { num: "iii.", tag: "Зал Комитаса · Ереван", h1: "",  h2: "Педагог",            p: "Ежегодные мастер-классы в Ереванской консерватории имени Комитаса и постоянная программа небольших фестивалей в регионах Армении. Преподавание здесь — не побочное занятие, а форма продолжающегося слушания." },
      { num: "iv.",  tag: "Resonance Editions",   h1: "",  h2: "Записывающийся артист", p: "Три студийных альбома на лейблах Resonance Editions и Yerevan Records. Сессии задуманы как документы — длинные дубли, минимум монтажа, ухо, обращённое к залу, а не к микрофону." },
    ],
    repertoire: [
      { h: "Концерты", items: [
        ["Бах",        "Концерты ля минор, ми мажор, ре минор (для двух скрипок)"],
        ["Моцарт",     "Концерты № 3, 4, 5"],
        ["Бетховен",   "Концерт ре мажор, соч. 61"],
        ["Мендельсон", "Концерт ми минор, соч. 64"],
        ["Брамс",      "Концерт ре мажор, соч. 77"],
        ["Чайковский", "Концерт ре мажор, соч. 35"],
        ["Сибелиус",   "Концерт ре минор, соч. 47"],
        ["Шостакович", "Концерт № 1 ля минор, соч. 77"],
        ["Хачатурян",  "Концерт ре минор"],
      ]},
      { h: "Соната и сольный концерт", items: [
        ["Бах",       "Шесть сонат и партит, BWV 1001–1006"],
        ["Бетховен",  "Сонаты № 5, 7, 9 («Крейцерова»)"],
        ["Брамс",     "Сонаты № 1, 2, 3"],
        ["Франк",     "Соната ля мажор"],
        ["Дебюсси",   "Соната соль минор"],
        ["Равель",    "Цыганка · Соната № 2"],
        ["Прокофьев", "Сонаты № 1, 2"],
        ["Шнитке",    "Соната № 1"],
      ]},
      { h: "Соло и современники", items: [
        ["Изаи",            "Шесть сонат, соч. 27"],
        ["Барток",          "Соната для скрипки соло, Sz. 117"],
        ["Берио",           "Sequenza VIII"],
        ["Куртаг",          "Знаки, игры и послания"],
        ["Комитас / перел.","Шесть армянских танцев"],
        ["Мансурян",        "Избранные миниатюры"],
        ["Пярт",            "Fratres · Spiegel im Spiegel"],
      ]},
    ],
    pressItems: [
      { q: "Фразировка редкого ума — Диланян играет линию, а не ноту.",                                            s: "Le Monde de la Musique", c: "Париж" },
      { q: "Сибелиус из гранита и льда. У него длинное дыхание, которого требует этот концерт.",                    s: "Helsingin Sanomat",      c: "Хельсинки" },
      { q: "Армянский голос в нём не спутать ни с чем — даже в Бахе. Здесь есть тишина, которая слушает.",          s: "Коммерсантъ",            c: "Москва" },
      { q: "Один из самых вдумчивых скрипачей своего поколения, ныне выступающих на сцене.",                       s: "The Strad",              c: "Лондон" },
    ],
    newsItems: [
      { d: "Апрель 2026",   t: "Дебют в Wigmore Hall подтверждён на весну 2027",                e: "Сольный концерт с пианисткой Анной Генюшас — Бах, Шнитке, Комитас — внесён в календарь Wigmore Hall на март 2027 года.", c: "Концерт" },
      { d: "Март 2026",     t: "Новый альбом «Northbound» вышел на Resonance Editions",         e: "Записанный за две недели в зале «Селло» в Эспоо, диск объединяет Сибелиуса с сонатами Пярта и Мансуряна.",            c: "Релиз" },
      { d: "Январь 2026",   t: "Мастер-классы в Ереване",                                        e: "Двухнедельная серия мастер-классов в Ереванской консерватории имени Комитаса, открытая для продвинутых струнников региона.", c: "Преподавание" },
      { d: "Ноябрь 2025",   t: "Первая премия Международного конкурса имени Хачатуряна",        e: "Первая премия и специальный приз зрительских симпатий в скрипичной номинации XX Международного конкурса имени Хачатуряна.", c: "Награда" },
    ],
    contact: {
      mgmt:  ["Менеджмент", ["Европейское представительство", "Albrecht & Strauch, Берлин", "office@albrecht-strauch.example"]],
      press: ["Пресса",     ["Эрин Мяки, пресс-атташе", "press@albertdilanyan.example"]],
      direct:["Напрямую",   ["albert@albertdilanyan.example"]],
      social:["Соцсети",    [["YouTube", "https://www.youtube.com/@АльбертАшотович-з8и"], ["Instagram", "—"], ["Spotify", "—"]]],
    },
    foot: "© 2026 Альберт Диланян. Все права защищены. Сайт — studio—lentus.",
    misc: { play: "Слушать", watch: "Смотреть", details: "Подробнее", season: "Сезон 2025 / 26" },
    filters: ["Все", "2026", "2025", "Прошедшие"],
    months: ["ЯНВ","ФЕВ","МАР","АПР","МАЙ","ИЮН","ИЮЛ","АВГ","СЕН","ОКТ","НОЯ","ДЕК"],
  },
};

// shared event data — independent of language for dates
const CONCERTS = [
  { iso: "2026-05-14", venue: "Helsinki Music Centre",   city: "Helsinki, FI",     program: { en: "Sibelius — Violin Concerto", fi: "Sibelius — Viulukonsertto", ru: "Сибелиус — Скрипичный концерт" }, withWhom: { en: "Finnish Radio Symphony · S. Mälkki", fi: "Radion sinfoniaorkesteri · S. Mälkki", ru: "Симфонический оркестр радио Финляндии · С. Мялкки" }, status: "available" },
  { iso: "2026-06-02", venue: "Tchaikovsky Concert Hall",city: "Moscow, RU",       program: { en: "Shostakovich — Concerto No. 1", fi: "Šostakovitš — Konsertto nro 1", ru: "Шостакович — Концерт № 1" },     withWhom: { en: "MGAFO · V. Yurowski",                    fi: "MGAFO · V. Jurovski",                       ru: "МГАФО · В. Юровский" },                              status: "available" },
  { iso: "2026-07-19", venue: "Verbier Festival",        city: "Verbier, CH",      program: { en: "Schnittke — Sonata No. 1 · Bach Partita II", fi: "Schnittke — Sonaatti nro 1 · Bach, Partita II", ru: "Шнитке — Соната № 1 · Бах, Партита II" }, withWhom: { en: "Recital · with A. Geniušas",            fi: "Resitaali · A. Geniušas",                    ru: "Концерт · с А. Генюшас" },                            status: "limited" },
  { iso: "2026-09-08", venue: "Komitas Chamber Hall",    city: "Yerevan, AM",      program: { en: "Bach · Komitas · Mansurian",                fi: "Bach · Komitas · Mansurjan",                    ru: "Бах · Комитас · Мансурян" },           withWhom: { en: "Solo recital",                            fi: "Soolokonsertti",                              ru: "Сольный концерт" },                                  status: "available" },
  { iso: "2026-10-21", venue: "Sage Gateshead",          city: "Newcastle, UK",    program: { en: "Brahms — Violin Concerto",                 fi: "Brahms — Viulukonsertto",                       ru: "Брамс — Скрипичный концерт" },          withWhom: { en: "Royal Northern Sinfonia · D. Boyd",      fi: "Royal Northern Sinfonia · D. Boyd",          ru: "Royal Northern Sinfonia · Д. Бойд" },                  status: "available" },
  { iso: "2027-03-15", venue: "Wigmore Hall",            city: "London, UK",       program: { en: "Bach · Schnittke · Komitas",                fi: "Bach · Schnittke · Komitas",                    ru: "Бах · Шнитке · Комитас" },              withWhom: { en: "Recital · with A. Geniušas",            fi: "Resitaali · A. Geniušas",                    ru: "Концерт · с А. Генюшас" },                            status: "available" },
  // past
  { iso: "2025-11-12", venue: "Khachaturian Hall",       city: "Yerevan, AM",      program: { en: "Khachaturian — Concerto",                  fi: "Hatšaturjan — Konsertto",                       ru: "Хачатурян — Концерт" },                 withWhom: { en: "Armenian State SO · E. Topchjan",       fi: "Armenian State SO · E. Topchjan",            ru: "Гос. симф. оркестр Армении · Э. Топчян" },              status: "past" },
  { iso: "2025-09-04", venue: "Moscow Conservatory",     city: "Moscow, RU",       program: { en: "Beethoven — Sonata Op. 47",                fi: "Beethoven — Sonaatti op. 47",                   ru: "Бетховен — Соната, соч. 47" },          withWhom: { en: "Recital · with A. Geniušas",            fi: "Resitaali · A. Geniušas",                    ru: "Концерт · с А. Генюшас" },                            status: "past" },
];

const ALBUMS = [
  { id: "northbound",  year: "2026", label: "Resonance Editions",   title: { en: "Northbound",          fi: "Northbound",          ru: "Northbound" },
    meta: { en: "Sibelius · Pärt · Mansurian", fi: "Sibelius · Pärt · Mansurjan", ru: "Сибелиус · Пярт · Мансурян" },
    mark: { line1: "N.B.", line2: "MMXXVI" },
    tracks: [
      { n: "01", t: { en: "Sibelius · Concerto · I. Allegro moderato", fi: "Sibelius · Konsertto · I. Allegro moderato", ru: "Сибелиус · Концерт · I. Allegro moderato" }, dur: "16:32" },
      { n: "02", t: { en: "Sibelius · Concerto · II. Adagio di molto",  fi: "Sibelius · Konsertto · II. Adagio di molto", ru: "Сибелиус · Концерт · II. Adagio di molto" }, dur: "08:14" },
      { n: "03", t: { en: "Pärt · Fratres",                              fi: "Pärt · Fratres",                              ru: "Пярт · Fratres" },                              dur: "10:01" },
      { n: "04", t: { en: "Mansurian · Lachrymae",                       fi: "Mansurjan · Lachrymae",                       ru: "Мансурян · Lachrymae" },                       dur: "06:48" },
    ]},
  { id: "partitas",    year: "2024", label: "Resonance Editions",   title: { en: "Partitas, vol. I",     fi: "Partitat, osa I",     ru: "Партиты, том I" },
    meta: { en: "Bach · BWV 1002 & 1004", fi: "Bach · BWV 1002 & 1004", ru: "Бах · BWV 1002 и 1004" },
    mark: { line1: "J. S. B.", line2: "BWV 1002 / 1004" },
    tracks: [
      { n: "01", t: { en: "Partita No. 1 · Allemanda",   fi: "Partita nro 1 · Allemanda",   ru: "Партита № 1 · Аллеманда" },   dur: "05:11" },
      { n: "02", t: { en: "Partita No. 1 · Corrente",     fi: "Partita nro 1 · Corrente",    ru: "Партита № 1 · Куранта" },     dur: "03:42" },
      { n: "03", t: { en: "Partita No. 2 · Sarabanda",    fi: "Partita nro 2 · Sarabanda",   ru: "Партита № 2 · Сарабанда" },   dur: "04:25" },
      { n: "04", t: { en: "Partita No. 2 · Ciaccona",     fi: "Partita nro 2 · Ciaccona",    ru: "Партита № 2 · Чакона" },      dur: "14:08" },
    ]},
  { id: "armeniaca",   year: "2022", label: "Yerevan Records",      title: { en: "Armeniaca",            fi: "Armeniaca",           ru: "Armeniaca" },
    meta: { en: "Komitas · Babadjanian · Bagdasaryan", fi: "Komitas · Babadjanjan · Bagdasarjan", ru: "Комитас · Бабаджанян · Багдасарян" },
    mark: { line1: "Կոմ.", line2: "MMXXII" },
    tracks: [
      { n: "01", t: { en: "Komitas · Krunk",                       fi: "Komitas · Krunk",                       ru: "Комитас · Кюнк" },                       dur: "04:33" },
      { n: "02", t: { en: "Komitas · Six Dances · No. 3",          fi: "Komitas · Kuusi tanssia · nro 3",       ru: "Комитас · Шесть танцев · № 3" },          dur: "03:18" },
      { n: "03", t: { en: "Babadjanian · Sonata · I",              fi: "Babadjanjan · Sonaatti · I",            ru: "Бабаджанян · Соната · I" },              dur: "07:05" },
      { n: "04", t: { en: "Bagdasaryan · Rhapsody",                fi: "Bagdasarjan · Rapsodia",                ru: "Багдасарян · Рапсодия" },                 dur: "09:26" },
    ]},
];

const VIDEOS = [
  { id: "feature", h: { en: "Sibelius · Concerto in D minor, op. 47 — live, Helsinki", fi: "Sibelius · Konsertto d-molli, op. 47 — live, Helsinki", ru: "Сибелиус · Концерт ре минор, соч. 47 — живая запись, Хельсинки" }, info: "Helsinki Music Centre · 2025 · 32:14" },
  { id: "v1", h: { en: "Bach · Chaconne, Partita No. 2",  fi: "Bach · Chaconne, Partita nro 2", ru: "Бах · Чакона, Партита № 2" }, info: "Komitas Hall · 2024", dur: "14:08" },
  { id: "v2", h: { en: "Schnittke · Sonata No. 1 · I",     fi: "Schnittke · Sonaatti nro 1 · I", ru: "Шнитке · Соната № 1 · I" },   info: "Sello, Espoo · 2025",  dur: "06:41" },
  { id: "v3", h: { en: "On the Armenian voice — interview",fi: "Armenialaisesta äänestä — haastattelu", ru: "Об армянском голосе — интервью" }, info: "Studio · 2025", dur: "09:22" },
];

window.COPY = COPY;
window.CONCERTS = CONCERTS;
window.ALBUMS = ALBUMS;
window.VIDEOS = VIDEOS;
